/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'balance_view': RouteRecordInfo<'balance_view', '/balance-view', Record<never, never>, Record<never, never>>,
    'currentState_view': RouteRecordInfo<'currentState_view', '/current-state-view', Record<never, never>, Record<never, never>>,
    'statistics': RouteRecordInfo<'statistics', '/statistics', Record<never, never>, Record<never, never>>,
    'home_view': RouteRecordInfo<'home_view', '/', Record<never, never>, Record<never, never>>,
    'operationsLog_view': RouteRecordInfo<'operationsLog_view', '/operations-log-view', Record<never, never>, Record<never, never>>,
    'wallet_view': RouteRecordInfo<'wallet_view', '/wallet-view', Record<never, never>, Record<never, never>>,
    'card-one_view': RouteRecordInfo<'card-one_view', '/card-one-view/:id', Record<never, never>, Record<never, never>>,
    'cards_view': RouteRecordInfo<'cards_view', '/cards-view', Record<never, never>, Record<never, never>>,
    'newCard_view': RouteRecordInfo<'newCard_view', '/new-card-view', Record<never, never>, Record<never, never>>,
  }
}
